# Generated by Django 5.1.1 on 2025-08-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='back_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_images/back/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='face_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_images/face/'),
        ),
    ]
