# Generated by Django 5.1.1 on 2025-08-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_customuser_back_id_image_customuser_face_id_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
