# Generated by Django 5.1.1 on 2025-08-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_customuser_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
