# Generated by Django 5.1.1 on 2025-08-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_customuser_is_staff_customuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('patient', 'Patient'), ('admin', 'Admin')], max_length=20),
        ),
    ]
