# Generated by Django 5.1.2 on 2025-08-01 19:37

from django.db import migrations
from datetime import date

def set_default_schedule_values(apps, schema_editor):
    DoctorSchedule = apps.get_model('Appointment', 'DoctorSchedule')
    for schedule in DoctorSchedule.objects.all():
        schedule.week_start_date = date(2000, 1, 1)
        schedule.is_recurring = True
        schedule.save()

class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_default_schedule_values),
    ]