# Generated by Django 5.1.1 on 2025-08-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_auto_20250801_2238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
